export const HOME_ROUTE = '/'
export const TERM_SERVICE_ROUTE = '/term-service'
export const CREATE_PASSWORD_ROUTE = '/create-password'
export const GENERATE_PHRASE_ROUTE = '/generate-phrase'
export const CONFIRM_PHRASE_ROUTE = '/confirm-phrase'
export const UNLOCK_ROUTE = '/unlock'
export const INITIALIZE_ROUTE = '/initialize'
