export const DEFAULT_ROUTE = '/'
export const TERM_SERVICE_ROUTE = '/term-service'
export const CREATE_PASSWORD_ROUTE = '/create-password'
export const UNLOCK_ROUTE = '/unlock'
export const INITIALIZE_ROUTE = '/initialize'
